services:
  - type: web
    name: competitive-intelligence-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8000
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: SUPERVITY_API_TOKEN
        sync: false
      - key: SUPERVITY_API_ORG
        sync: false
      - key: SUPERVITY_AGENT_ID
        sync: false
      - key: SUPERVITY_SKILL_ID
        sync: false
      - key: SUPERVITY_EMAIL_AGENT_ID
        sync: false
      - key: SUPERVITY_EMAIL_SKILL_ID
        sync: false
    healthCheckPath: /health
    
  - type: web
    name: competitive-intelligence-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: PORT
        value: 8501
      - key: API_BASE_URL
        fromService:
          type: web
          name: competitive-intelligence-backend
          envVarKey: RENDER_EXTERNAL_URL 